### PR TITLE
Improve Exported ImagePlus Calibration

### PR DESCRIPTION
**Pull request by tischi**
@NicoKiaru

### CODE REVIEW

**Comment by tischi** [comment]
@NicoKiaru 
Please wait with the merge. I am discovering more issues.
If the image is rotated in BDV (e.g. `shift+X`) then wrong axis calibrations are assigned to the imagePlus. Axis are permuted and also the signs of both the calibration and the offsets are wrong. I am investigating...

**Comment by tischi** [comment]
Could you explain what the reasoning of this formula is? You are computing the sum squares of all the columns, isn't it?

```
static void storeMatrixToImagePlus(ImagePlus imp, AffineTransform3D at3D) {
        Calibration cal = new Calibration();

        double[] m = at3D.getRowPackedCopy();
        double voxX = Math.sqrt(m[0]*m[0]+m[4]*m[4]+m[8]*m[8]);
        double voxY = Math.sqrt(m[1]*m[1]+m[5]*m[5]+m[9]*m[9]);
        double voxZ = Math.sqrt(m[2]*m[2]+m[6]*m[6]+m[10]*m[10]);

        cal.pixelWidth = voxX;
        cal.pixelHeight = voxY;
        cal.pixelDepth = voxZ;
```

**Comment by tischi** [comment]
I think I get it. The values in the columns determine the length of unit vectors in the calibrated coordinate system. The issue is just that this formula looses the sign of the direction, which is important when we rotate the image.

I am currently experimenting with below transformation:
```
                 2.0,  0.0,  0.0, -57.978333333333296, 
                 0.0,  0.0,  1.0, 36.18833333333334, 
                 0.0, -2.0,  0.0, 197.79999999999998
```

By visual inspection and playing a bit around I found that the correct calibration for the ImagePlus would be:

```
calX = 2;
calY = -2; // yes negative, but that gives the correct values
calZ = 1;
originX = 28; // = -1 * -57.97 / 2
originY = 98; //  = -1 * 197.79 / -2
originZ = -36; // = -1 * 36
```

Apparently the information is in the affine, but we have to figure out how to extract it properly. Probably easy enough, but need some sleep now 🛌 😺

**Comment by tischi** [comment]
...of course I could not stop 🤔 

This seems to give the right `cal.origin`:

```
 final double[] origin = new double[ 3 ];
 transform3D.inverse().apply( new double[3], origin );
```

**Comment by NicoKiaru** [comment]
Ahaha, good job, but get some rest. I won't have time to take care of this today, but tomorrow I can merge do some merge and new version

**Comment by NicoKiaru** [comment]
It's all good ? Can I merge and make a new version?

Thanks for improving this!

**Comment by tischi** [comment]
Yes, I think that should work.
I would love to test it first with the ellipsoid transformed image, but I cannot due to the singular matrix error...
Maybe then just merge and release and hope for the best?

**Pull request merged**
